# Form implementation generated from reading ui file 'Qt2better.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(713, 579)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 631, 81))
        self.label_2.setStyleSheet("QLabel {\n"
"color: #20004b;\n"
"    font-size:20px;\n"
"    font-family: \'Mulish\', Arial, sans-serif;\n"
"    line-height: 1.1;\n"
"    font-weight: 800;\n"
"    border-radius: 10px;\n"
"    background-position: center center;\n"
"    background-size: cover;\n"
"    background-repeat: no-repeat;\n"
"    border-color: transparent;\n"
"     border-style: solid;\n"
"   display: table-cell;\n"
"    vertical-align: middle;\n"
"    width: 100%;\n"
"    -webkit-text-size-adjust: 100%;\n"
"border-radius: 10px;\n"
"    background-color: #ffde00;\n"
"    background-position: center center;\n"
"    border-color: transparent;\n"
"    border-style: solid;\n"
"    transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out, border-color 0.2s ease-in-out;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 350, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Mulish,Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-family: \'Mulish\', Arial, sans-serif;\n"
"    line-height: 1.55;\n"
"    font-weight: 700;\n"
"    border-radius: 10px;\n"
"    background-color: #ad26ff;\n"
"    background-position: center center;\n"
"    border-color: transparent;\n"
"    border-style: solid;\n"
"    transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out, border-color 0.2s ease-in-out;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 350, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Mulish,Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-family: \'Mulish\', Arial, sans-serif;\n"
"    line-height: 1.55;\n"
"    font-weight: 700;\n"
"    border-radius: 10px;\n"
"    background-color: #ad26ff;\n"
"    background-position: center center;\n"
"    border-color: transparent;\n"
"    border-style: solid;\n"
"    transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out, border-color 0.2s ease-in-out;\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "                                                        Вопрос"))
        self.pushButton.setText(_translate("Dialog", "Да"))
        self.pushButton_2.setText(_translate("Dialog", "Нет"))
